import Link from "next/link";
import { AppShell } from "@/components/AppShell";
import { PendingSubmitButton } from "@/components/PendingSubmitButton";
import { ConfirmSubmitButton } from "@/components/ConfirmSubmitButton";
import { requireTenantActor } from "@/middleware/rbac";
import { hasCapability } from "@/lib/rbac/access";
import { getReports } from "@/services/reportingService";
import { exportFinanceHandoffAction } from "@/app/employees/actions";
import { exportTenantDataAction } from "@/app/setup/actions";
import { getCountryName } from "@/lib/geo/countries";

export const dynamic = "force-dynamic";
const views = [["headcount", "Headcount"], ["joiners", "Joiners & leavers"], ["time-off", "Time off"], ["away", "Who's away"], ["documents", "Documents"], ["onboarding", "Onboarding & probation"], ["policies", "Policy acknowledgements"], ["exports", "Exports"]] as const;
const today = () => new Date().toISOString().slice(0, 10);
const yearAgo = () => { const d = new Date(); d.setUTCFullYear(d.getUTCFullYear() - 1); return d.toISOString().slice(0, 10); };
const human = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (c) => c.toUpperCase());
const num = (value: number) => new Intl.NumberFormat("en", { maximumFractionDigits: 1 }).format(value);

function Table({ heads, rows }: { heads: string[]; rows: Array<Array<React.ReactNode>> }) {
  return <div className="mt-5 overflow-x-auto border-y border-ink-200/70"><table className="min-w-full text-left text-[13px]"><thead className="border-b border-ink-200/70"><tr>{heads.map((h) => <th key={h} className="px-4 py-3 text-[11px] font-semibold tracking-wide text-ink-500">{h}</th>)}</tr></thead><tbody className="divide-y divide-ink-100">{rows.length ? rows.map((row, i) => <tr key={i}>{row.map((cell, j) => <td key={j} className="px-4 py-3 text-ink-700">{cell}</td>)}</tr>) : <tr><td colSpan={heads.length} className="px-4 py-8 text-center text-ink-500">No records for this selection.</td></tr>}</tbody></table></div>;
}

function HeadcountTrend({ rows }: { rows: Array<{ month: string; count: number }> }) {
  const max = Math.max(1, ...rows.map((row) => row.count));
  return <figure className="tf-surface-flat mt-6 p-5" aria-labelledby="headcount-trend-title"><figcaption id="headcount-trend-title" className="text-[13px] font-semibold text-ink-800">12-month headcount trend</figcaption><div className="mt-5 flex h-44 items-end gap-2 border-b border-ink-200" role="img" aria-label={rows.map((row) => `${row.month}: ${row.count}`).join(", ")}>{rows.map((row) => <div key={row.month} className="flex min-w-0 flex-1 flex-col items-center justify-end gap-2"><span className="text-[10px] tabular-nums text-ink-500">{row.count}</span><span className="w-full rounded-t bg-ink-700" style={{ height: `${Math.max(3, row.count / max * 120)}px` }} /><span className="w-full truncate text-center text-[9px] text-ink-400" title={row.month}>{row.month.split(" ")[0]}</span></div>)}</div></figure>;
}

function WorkforceMovement({ joiners, leavers }: { joiners: Array<{ start_date: string | null }>; leavers: Array<{ end_date: string | null }> }) {
  const months = [...new Set([...joiners.flatMap((item) => item.start_date ? [item.start_date.slice(0, 7)] : []), ...leavers.flatMap((item) => item.end_date ? [item.end_date.slice(0, 7)] : [])])].sort();
  const rows = months.map((month) => ({ month, joined: joiners.filter((item) => item.start_date?.startsWith(month)).length, left: leavers.filter((item) => item.end_date?.startsWith(month)).length }));
  const max = Math.max(1, ...rows.flatMap((row) => [row.joined, row.left]));
  return <figure className="tf-surface-flat mt-6 p-5" aria-labelledby="movement-title"><figcaption id="movement-title" className="text-[13px] font-semibold text-ink-800">Monthly workforce movement</figcaption>{rows.length ? <div className="mt-5 flex h-44 items-end gap-4 border-b border-ink-200" role="img" aria-label={rows.map((row) => `${row.month}: ${row.joined} joined, ${row.left} left`).join(", ")}>{rows.map((row) => <div key={row.month} className="flex min-w-0 flex-1 flex-col items-center gap-2"><div className="flex h-32 items-end gap-1"><span className="w-3 rounded-t bg-ink-800" style={{ height: `${Math.max(2, row.joined / max * 110)}px` }} title={`${row.joined} joined`} /><span className="w-3 rounded-t bg-ink-300" style={{ height: `${Math.max(2, row.left / max * 110)}px` }} title={`${row.left} left`} /></div><span className="text-[9px] text-ink-400">{row.month}</span></div>)}</div> : <p className="mt-4 text-[13px] text-ink-500">No joiners or leavers in this period.</p>}<p className="mt-3 text-[11px] text-ink-500"><span className="font-semibold text-ink-800">Dark:</span> joined · <span className="font-semibold text-ink-400">Light:</span> left</p></figure>;
}

export default async function ReportsPage({ searchParams }: { searchParams: Promise<{ view?: string; from?: string; to?: string; department?: string; location?: string }> }) {
  const actor = await requireTenantActor();
  if (actor.role !== "admin") return null;
  const params = await searchParams;
  const view = views.some(([id]) => id === params.view) ? params.view! : "headcount";
  const filters = { from: params.from ?? yearAgo(), to: params.to ?? today(), department: params.department || undefined, location: params.location || undefined };
  const report = await getReports(actor, filters, { includeBalances: view === "time-off" });
  const canFinance = await hasCapability(actor, "finance_payroll_exports");
  const canFull = await hasCapability(actor, "company_access_settings");
  const query = new URLSearchParams({ from: filters.from, to: filters.to, ...(filters.department ? { department: filters.department } : {}), ...(filters.location ? { location: filters.location } : {}) });
  const csvLink = `/reports/export?report=${encodeURIComponent(view)}&${query}`;
  return <main className="mx-auto max-w-6xl px-6 py-14"><AppShell actor={actor} activePath="/reports" />
    <header className="border-b border-ink-300/60 pb-5"><p className="text-[12px] tracking-[0.14em] text-ink-500">Workforce information</p><h1 className="mt-2 text-[34px] tracking-tight">Reports</h1><p className="mt-1 text-[14px] text-ink-500">Fixed HR reports for clear workforce answers. Actions remain on Home.</p></header>
    <nav className="tf-secondary-nav tf-reports-nav mt-7" aria-label="Reports">{views.map(([id, label]) => <Link key={id} href={`/reports?view=${id}`} aria-current={view === id ? "page" : undefined}>{label}</Link>)}</nav>
    {view !== "exports" ? <form className="tf-filter-strip mt-5 md:grid-cols-[1fr_1fr_1.2fr_1.2fr_auto]"><input type="hidden" name="view" value={view}/><label className="text-[12px] text-ink-600">From<input type="date" name="from" defaultValue={filters.from} className="tf-input mt-1"/></label><label className="text-[12px] text-ink-600">To<input type="date" name="to" defaultValue={filters.to} className="tf-input mt-1"/></label><label className="text-[12px] text-ink-600">Department<select name="department" defaultValue={filters.department ?? ""} className="tf-select mt-1"><option value="">All</option>{report.departments.map((v) => <option key={v}>{v}</option>)}</select></label><label className="text-[12px] text-ink-600">Location<select name="location" defaultValue={filters.location ?? ""} className="tf-select mt-1"><option value="">All</option>{report.locations.map((v) => <option key={v}>{v}</option>)}</select></label><button className="tf-secondary-action self-end px-4 py-2 text-[13px]">Apply</button></form> : null}
    <section className="mt-7">
      {view === "headcount" ? <><div className="flex items-start justify-between gap-4"><div><h2 className="tf-h2">Headcount</h2><p className="mt-1 text-[13px] text-ink-500">Current people, including pre-start employees, and the recorded 12-month workforce trend.</p></div><a className="tf-secondary-action px-3 py-2 text-[12px]" href={csvLink}>Download CSV</a></div><div className="tf-summary mt-5"><div><div className="tf-summary-label">Current people</div><div className="tf-summary-value">{report.active.length}</div></div><div><div className="tf-summary-label">Departments</div><div className="tf-summary-value">{report.byDepartment.length}</div></div><div><div className="tf-summary-label">Locations</div><div className="tf-summary-value">{report.byLocation.length}</div></div></div><HeadcountTrend rows={report.trend}/><div className="mt-7 grid gap-6 lg:grid-cols-2"><Table heads={["Month", "Headcount"]} rows={report.trend.map((r) => [r.month, r.count])}/><Table heads={["Department", "People"]} rows={report.byDepartment.map(([k, v]) => [k, v])}/><Table heads={["Location", "People"]} rows={report.byLocation.map(([k, v]) => [k, v])}/><Table heads={["Employment type", "People"]} rows={report.byEmployment.map(([k, v]) => [human(k), v])}/><Table heads={["Country", "People"]} rows={report.byCountry.map(([k, v]) => [getCountryName(k) ?? k, v])}/></div></> : null}
      {view === "joiners" ? <><div className="flex justify-between"><div><h2 className="tf-h2">Joiners &amp; leavers</h2><p className="mt-1 text-[13px] text-ink-500">Turnover = leavers during the period ÷ average recorded monthly headcount.</p></div><a className="tf-secondary-action px-3 py-2 text-[12px]" href={csvLink}>Download CSV</a></div><div className="tf-summary mt-5"><div><div className="tf-summary-label">Joiners</div><div className="tf-summary-value">{report.joiners.length}</div></div><div><div className="tf-summary-label">Leavers</div><div className="tf-summary-value">{report.leavers.length}</div></div><div><div className="tf-summary-label">Turnover</div><div className="tf-summary-value">{report.turnover === null ? "—" : `${num(report.turnover)}%`}</div></div></div><WorkforceMovement joiners={report.joiners} leavers={report.leavers}/><Table heads={["Person", "Department", "Event", "Date"]} rows={[...report.joiners.map((e) => [<Link className="font-semibold underline" href={`/people/${e.id}`} key={e.id}>{e.full_name}</Link>, e.department, "Joined", e.start_date]), ...report.leavers.map((e) => [<Link className="font-semibold underline" href={`/people/${e.id}`} key={e.id}>{e.full_name}</Link>, e.department, "Left", e.end_date])]}/></> : null}
      {view === "time-off" ? <><div className="flex justify-between"><div><h2 className="tf-h2">Time off</h2><p className="mt-1 text-[13px] text-ink-500">The same entitlement, opening balance and request calculation used in Time off.</p></div><a className="tf-secondary-action px-3 py-2 text-[12px]" href={csvLink}>Download CSV</a></div><Table heads={["Person", "Type", "Entitlement", "Taken", "Pending", "Available"]} rows={report.balanceRows.map((row) => [<Link className="font-semibold underline" href={`/people/${row.employee.id}#time-off`} key={`${row.employee.id}:${row.definition_id}`}>{row.employee.full_name}</Link>, row.display_name, row.entitlement ?? "—", num(row.taken), num(row.pending), row.available ?? "—"])}/></> : null}
      {view === "away" ? <><div className="flex justify-between"><div><h2 className="tf-h2">Who&apos;s away</h2><p className="mt-1 text-[13px] text-ink-500">Approved leave overlapping the selected period.</p></div><a className="tf-secondary-action px-3 py-2 text-[12px]" href={csvLink}>Download CSV</a></div><Table heads={["Person", "Department", "Leave type", "From", "To", "Days"]} rows={report.away.map((l) => { const e = report.employees.find((x) => x.id === l.employee_id); return [e?.full_name ?? "Unknown", e?.department ?? "—", human(l.leave_type), l.start_date, l.end_date, num(Number(l.requested_days))]; })}/></> : null}
      {view === "documents" ? <><div className="flex justify-between"><div><h2 className="tf-h2">Documents</h2><p className="mt-1 text-[13px] text-ink-500">Complete means every configured required document is accepted.</p></div><a className="tf-secondary-action px-3 py-2 text-[12px]" href={csvLink}>Download CSV</a></div><Table heads={["Person", "Required", "Approved", "Completeness", "Outstanding", "Awaiting review", "Expired"]} rows={report.requirementRows.map((r) => [<Link className="font-semibold underline" href={`/people/${r.employee.id}#documents`} key={r.employee.id}>{r.employee.full_name}</Link>, r.required, r.accepted, r.required ? `${Math.round(r.accepted / r.required * 100)}%` : "—", r.outstanding, r.review, r.expired])}/><p className="mt-4 text-[12px] text-ink-500">{report.expiry.length} documents expire within 90 days.</p></> : null}
      {view === "onboarding" ? <><div className="flex justify-between"><div><h2 className="tf-h2">Onboarding &amp; probation</h2><p className="mt-1 text-[13px] text-ink-500">Checklist progress, overdue work, check-ins and probation.</p></div><a className="tf-secondary-action px-3 py-2 text-[12px]" href={csvLink}>Download CSV</a></div><Table heads={["Person", "Checklist", "Overdue", "Check-ins", "Probation"]} rows={report.onboardingRows.filter((r) => r.tasks || r.checkIns.length || r.probation.length).map((r) => [<Link className="font-semibold underline" href={`/people/${r.employee.id}#onboarding-offboarding`} key={r.employee.id}>{r.employee.full_name}</Link>, r.tasks ? `${Math.round(r.complete / r.tasks * 100)}%` : "—", r.overdue, r.checkIns.map((c) => human(c.status)).join(", ") || "—", r.probation.map((p) => p.outcome ? human(p.outcome) : human(p.status)).join(", ") || "—"])}/></> : null}
      {view === "policies" ? <><div className="flex justify-between"><div><h2 className="tf-h2">Policy acknowledgements</h2><p className="mt-1 text-[13px] text-ink-500">Published policy versions and each active person&apos;s acknowledgement.</p></div><a className="tf-secondary-action px-3 py-2 text-[12px]" href={csvLink}>Download CSV</a></div><div className="tf-summary mt-5"><div><div className="tf-summary-label">Required</div><div className="tf-summary-value">{report.policyRows.length}</div></div><div><div className="tf-summary-label">Outstanding</div><div className="tf-summary-value">{report.policyRows.filter((r) => !r.acknowledgement).length}</div></div></div><Table heads={["Policy", "Version", "Person", "Status", "Date"]} rows={report.policyRows.map((r) => [r.policy.title, r.policy.version, r.employee.full_name, r.acknowledgement ? "Acknowledged" : "Outstanding", r.acknowledgement?.acknowledged_at.slice(0, 10) ?? "—"])}/></> : null}
      {view === "exports" ? <><h2 className="tf-h2">Exports</h2><p className="mt-1 text-[13px] text-ink-500">The single home for organisation-wide exports.</p><div className="mt-6 grid gap-4 md:grid-cols-2"><section className="rounded-xl border border-ink-200 p-5"><h3 className="font-bold">Payroll export</h3><p className="mt-1 text-[13px] text-ink-500">Finance handoff in spreadsheet-friendly formats.</p>{canFinance ? <form action={exportFinanceHandoffAction} className="mt-4"><input type="hidden" name="return_to" value="/reports?view=exports"/><PendingSubmitButton idleLabel="Export payroll data" pendingLabel="Preparing…" className="tf-primary-action px-4 py-2 text-[13px]"/></form> : <p className="mt-4 text-[13px] text-ink-500">Finance export access is required.</p>}</section><section className="rounded-xl border border-ink-200 p-5"><h3 className="font-bold">Full data export</h3><p className="mt-1 text-[13px] text-ink-500">Portable tenant records and uploaded documents.</p>{canFull ? <form action={exportTenantDataAction} className="mt-4"><ConfirmSubmitButton idleLabel="Export all TeamFrame data" pendingLabel="Preparing…" className="tf-primary-action px-4 py-2 text-[13px]" confirmMessage="Prepare a private full installation export?"/></form> : <p className="mt-4 text-[13px] text-ink-500">Full Access is required.</p>}</section></div></> : null}
    </section>
  </main>;
}
