-- The launch project disables automatic API grants for newly created tables.
-- TeamFrame's service layer uses the server-only service_role key for data
-- operations. Keep the table list explicit: no anon/authenticated table grants,
-- no future-table default privileges, and no RLS or storage-policy changes.
grant select, insert, update, delete on table
  public.acknowledgements,
  public.action_items,
  public.analytics_events,
  public.audit_logs,
  public.companies,
  public.company_holidays,
  public.compensation,
  public.compensation_component_amounts,
  public.compensation_components,
  public.compensation_history,
  public.departments,
  public.document_requirements,
  public.documents,
  public.employee_join_initializations,
  public.employee_payment_details,
  public.employee_profiles,
  public.employees,
  public.employment_changes,
  public.export_files,
  public.file_operations,
  public.hr_automation_events,
  public.hr_automation_items,
  public.leave_definitions,
  public.leave_opening_adjustments,
  public.leaves,
  public.offboarding_cases,
  public.offboarding_items,
  public.onboarding_check_ins,
  public.onboarding_tasks,
  public.policies,
  public.position_assignments,
  public.positions,
  public.probation_reviews,
  public.procedures,
  public.risk_signals,
  public.setup_import_batches,
  public.tenant_access_invitations,
  public.tenant_memberships,
  public.work_locations
to service_role;
